#!/usr/bin/env php
<?php

declare(strict_types=1);

use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

/** @var ContainerInterface $container */
$container = require __DIR__ . '/bootstrap/app.php';

/** @var Application $cli */
$cli = $container->get(Application::class);

$cli->addCommands([
    // add commands here
]);

$cli->run();