services:
  php:
    build: "."
    ports:
      - "443:443/udp"
      - "443:443"
      - "80:80"
    volumes:
      - "$PWD/:/app"
      - "caddy_data:/data"
      - "caddy_config:/config"
    environment:
      - FRANKENPHP_CONFIG=worker ./public/index.php
      - MAX_REQUESTS=1000 # needs finetuning

volumes:
  caddy_data:
  caddy_config:
